# Generated by Django 5.1.6 on 2025-02-26 14:33

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AIAnswers',
            fields=[
            ],
            options={
                'db_table': 'ai_answers',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Articles',
            fields=[
            ],
            options={
                'db_table': 'articles',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Conversations',
            fields=[
            ],
            options={
                'db_table': 'conversations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UserQuestions',
            fields=[
            ],
            options={
                'db_table': 'user_questions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
            ],
            options={
                'db_table': 'users',
                'managed': False,
            },
        ),
    ]
