# Generated by Django 5.1.7 on 2025-03-14 10:24

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conversations',
            fields=[
            ],
            options={
                'db_table': 'conversations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
            ],
            options={
                'db_table': 'messages',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
            ],
            options={
                'db_table': 'users',
                'managed': False,
            },
        ),
    ]
